### ISSUE TITLE
Question: Is it good to have one single function when deploying serverless?

### ISSUE THREAD

**Issue by SanskarSans** [jthegedus/firebase-gcp-examples#105]

**Comment by jthegedus** [comment]
Hi @SanskarSans can you elaborate further? Is this a question in general or related to a specific example?

**Comment by SanskarSans** [comment]
I do not have quite experience on serverless. I am new to both nextjs and serverless. Forgive me if I am wrong. My concern is if we have only one cloud function for everything(for all routes) and importing them all in one function instead of one cloud function for one route then wont this slow down cold boot? 

suppose in the case of nextjs, let's say we have 100 pages i.e 100 routes. Now if we have only 1 cloud function for those 100 routes then it might take considerable amount of time to cold boot. what if we have one cloud function for each route while building the output? 

I hope you understood my concern.

**Comment by jthegedus** [comment]
I wouldn't worry about it until it is measured and proven to be a problem. The Next.js server only really performs the React SSR functions plus some other logic, I wouldn't expect it to be a computationally intensive process.

Cloud Functions have a default memory of `256MB` which comes with a CPU of `400MHz`, if this is not enough for you particular needs you can bump it up to `2048MB` with `2.4GHz` - https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation (see matching CPU here https://cloud.google.com/functions/pricing#compute_time)

Ultimately, the time it takes for a Cloud Function to Cold-boot depends on the way dependencies are imported in the code. I expect the Next.js server when compiled and deployed manages importing and eval of code efficiently, though I have no data to back this up, other than I haven't seen people have problems with this.

With the latest APIs performing static builds of pages that do not request data, and SGG pages being able to be rendered at build time, I don't expect the performance to be bad for these routes as it is simply a file lookup and setting of cache-controls. SSR and iSSG (with fallback:true) incur the most computational cost as the React SSR code needs to run and data fetching.

I hope this explanation helps.

If the cold-starts become a problem, I would suggest looking at the `cloudrun-nextjs` example as this uses [Google Cloud Run](https://cloud.google.com/run) which can handle [multiple requests at once](https://cloud.google.com/run/docs/about-concurrency), thus, only executing the startup code once for many many requests.

**Comment by SanskarSans** [comment]
this is super helpful information. Thank you very much for explaining neatly.

**Comment by jthegedus** [comment]
@SanskarSans 

The Next.js docs received an update to show the a lot of code is removed when bundled. For instance, this example shows the code used in SSG mode doesn't show up in the client - https://next-code-elimination.now.sh/

It's the fact that the Next.js team is performing optimisations like this that I won't worry about the performance until it is measurably causing me issues.
