### ISSUE TITLE
Incremental Static Regeneration

### ISSUE THREAD

**Issue by danaugrs** [jthegedus/firebase-gcp-examples#140]
First of all, thank you @jthegedus for putting together these amazing resources!

I'm trying to use [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration) with [functions-nextjs](https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs) but haven't been able to get it working.

The only necessary change is to add e.g. `revalidate: 1` (for 1 second) inside the returned `props` below:

https://github.com/jthegedus/firebase-gcp-examples/blob/c6f1ab62325ca2cf759a881ff434357039be95dd/functions-nextjs/pages/blog/%5Bpid%5D.js#L27-L51

Have you tried it? Do you know if there are any fundamental limitations?

**Comment by jthegedus** [comment]
Hi @danaugrs

This example was built while iSSG was still experimental. iSSG is enabled, but the flag to do so was removed in the last release of Next.js when the feature was promoted to stable, so it's probably not working now. I'll look into updating the example soon.

**Comment by jthegedus** [comment]
Updated :tada:
