### ISSUE TITLE
next rebuilding the project on each request (in emulator)

### ISSUE THREAD

**Issue by rostyslavnikitin** [jthegedus/firebase-gcp-examples#157]
I trying to use "**functions-nextjs**".
just on each request that I send to localhost:5000, it starts rebuilding, and files from the dist folder disappear that creates an error. I start in the emulator, maybe it's cause?

**Comment by qnxdev** [comment]
Any update?

**Comment by jthegedus** [comment]
Maybe this thread will help - https://github.com/jthegedus/firebase-gcp-examples/issues/29
