### ISSUE TITLE
TypeError: _onRequestWithOpts is not a function

### ISSUE THREAD

**Issue by umxr** [jthegedus/firebase-gcp-examples#68]
Not sure if this is a configuration issue on my end or if the boilerplate doesnt work. im just running some of the setup commands in the package.json. everything runs fine but when i run `yarn serve` i get this error.

<img width="1329" alt="Screenshot 2019-07-27 at 09 46 10" src="https://user-images.githubusercontent.com/20203468/61992256-a6e04300-b053-11e9-91eb-9f7cf37a2d83.png">

**Comment by jthegedus** [comment]
Can you try this again after updating to the latest `firebase-tools`?

`yarn add firebase-tools@latest`

**Comment by umxr** [comment]
Nice! working perfectly thanks

**Comment by jthegedus** [comment]
Glad I could help. I'll update the deps of the example soon. Thanks for raising this :smiley:
