### ISSUE TITLE
"Not Working" on folder/files

### ISSUE THREAD

**Issue by douglasjkruse-work** [jthegedus/firebase-gcp-examples#84]
Hi

Just curious if the "not working" note on some of the folders/files is still valid?

Thanks!

**Comment by jthegedus** [comment]
Are you referring to `firebase serve` in particular? I haven't run each of these examples in some time. 🤔 Might setup some tests to do so

**Comment by douglasjkruse-work** [comment]
Yes sir, the Firebase + Next.js example in particular.  Thanks!

**Comment by jthegedus** [comment]
Ah yes, the Next.js one. The example in this repo is different to the last and may not be subject to the same "not working" statements I made about the previous example.

**Comment by jthegedus** [comment]
My new Next.js example is out which does use the new Firebase Emulator - https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs

It is of note however, that there are many issues running the next.js development server on a Cloud Function locally.
