### ISSUE TITLE
All files in public/static directory does not work on dev server (yarn watch)

### ISSUE THREAD

**Issue by Baystef** [jthegedus/firebase-gcp-examples#90]
## Which Package & Your Environment

* Package in this repo: firebase-nextjs
* OS: windows 10
* Node Version: v10.15.3
* Pkg Manager: npm
* Shell:
* Browser & version: chrome(latest)
* Language: javascript (nodejs)

## Expected Behaviour

When the development server is started with `yarn watch`, static files like images in the `public/static` directory should be rendered in the application.

## Actual Behaviour

when dev server is started with `yarn watch`, all images in `public/static` are not rendered and in the browser console it returns errors for all images and files in the public folder in this format `http://localhost:3000/static/img/{imageName}.svg 404 (Not Found)`.  But when the application is deployed with `yarn deploy`, all the images are rendered fine with no error

Public folder structure
```javascript
- public
      - static
           - img
                - image.svg
```
all other configurations and file structure are exactly the same according to the repo

## Possible Solution
Make a copy of the static folder and paste it in `src/client`, this solves the issue on local development server and all static files work now but there should be a better way of solving this. So now the static files for development server are in `src/client/static` and those for firebase are in `public/static`

## Context

This issue has made development impossible as some static files are crucial for the application to work. If the static files don't work locally, then there's no way to develop on dev server

**Comment by maotora** [comment]
I have always kept my static files in `/src/client/public` for development (Next.js way) and when it's time to publish/deploy I copy everything in my `/src/client/public` to `%project_root%/public`.

You could also write a pre-deploy npm script that does this automatically.

**Comment by jthegedus** [comment]
Hi all, this is solved in my new example https://github.com/jthegedus/firebase-gcp-examples/tree/master/functions-nextjs

Please take a look as it is more simplified in structure, but also a better example of the multiple Next.js features now available
